In [7]:
import torch
import torch.nn.functional as F
import numpy as np

###Реализация функции Convolution 2D

In [8]:
def Convolution2D(image, kernel, stride = 1, padding = 0):
    #stride - шаг, с помощью которого мы двигаем ядро свёртки по входному тензору
    #нахождение размеров изображения и ядра
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    #нахождение размеров результирующего изображения
    result_height = int((image_height - kernel_height + 2 * padding) / stride) + 1
    result_width = int((image_width - kernel_width + 2 * padding) / stride) + 1
    #создание результирующего изображения
    result = np.zeros((result_height, result_width))
    #добавление padding (добавление нулей вокруг входной матрицы)
    if padding > 0:
        image = np.pad(image, padding, mode = 'constant')
    #проход ядром по изображению
    for y in range(result_height):
        for x in range(result_width):
            result[y, x] = np.sum(image[y*stride:y*stride+kernel_height, x*stride:x*stride+kernel_width] * kernel)
    return result

###Тест 1

In [9]:
image = torch.randn(1, 1, 5, 5)  #задание изображения
kernel = torch.randn(1, 1, 3, 3)  #задание ядра свёртки
#результат использования нашей функции Convolution2D
test1_output1 = Convolution2D(image[0, 0].numpy(), kernel[0, 0].numpy())
print("Результат использования нашей функции Convolution2D в тесте 1:")
print(test1_output1)
print("\nРезультат использования функции Conv2d библиотеки PyTorch в тесте 1:")
test1_output2 = F.conv2d(image, kernel)
print(test1_output2)

Результат использования нашей функции Convolution2D в тесте 1:
[[ 0.49464083  3.51855898  1.39028502]
 [ 0.10425329  2.86361623  1.90627527]
 [ 0.80307114  4.48781681 -3.52397227]]

Результат использования функции Conv2d библиотеки PyTorch в тесте 1:
tensor([[[[ 0.4946,  3.5186,  1.3903],
          [ 0.1043,  2.8636,  1.9063],
          [ 0.8031,  4.4878, -3.5240]]]])


###Тест 2

In [10]:
image = torch.randn(1, 1, 5, 5)  #задание изображения
kernel = torch.randn(1, 1, 3, 3)  #задание ядра свёртки
#результат использования нашей функции Convolution2D
test2_output1 = Convolution2D(image[0, 0].numpy(), kernel[0, 0].numpy())
print("Результат использования нашей функции Convolution2D в тесте 2:")
print(test2_output1)
print("\nРезультат использования функции Conv2d библиотеки PyTorch в тесте 2:")
test2_output2 = F.conv2d(image, kernel)
print(test2_output2)

Результат использования нашей функции Convolution2D в тесте 2:
[[ 0.07428968  0.11373711 -2.14445972]
 [-0.95122957 -0.96126676 -2.47257471]
 [ 0.77612293  1.06222141 -1.62786138]]

Результат использования функции Conv2d библиотеки PyTorch в тесте 2:
tensor([[[[ 0.0743,  0.1137, -2.1445],
          [-0.9512, -0.9613, -2.4726],
          [ 0.7761,  1.0622, -1.6279]]]])


###Тест 3

In [12]:
image = torch.randn(1, 1, 5, 5)  #задание изображения
kernel = torch.randn(1, 1, 3, 3)  #задание ядра свёртки
#результат использования нашей функции Convolution2D
test3_output1 = Convolution2D(image[0, 0].numpy(), kernel[0, 0].numpy())
print("Результат использования нашей функции Convolution2D в тесте 3:")
print(test3_output1)
print("\nРезультат использования функции Conv2d библиотеки PyTorch в тесте 3:")
test3_output2 = F.conv2d(image, kernel)
print(test3_output2)

Результат использования нашей функции Convolution2D в тесте 3:
[[-0.15780884 -2.11644721 -0.08168559]
 [ 0.47271878 -2.3847003  -0.57830918]
 [ 3.32607532 -1.11378038 -3.27566242]]

Результат использования функции Conv2d библиотеки PyTorch в тесте 3:
tensor([[[[-0.1578, -2.1164, -0.0817],
          [ 0.4727, -2.3847, -0.5783],
          [ 3.3261, -1.1138, -3.2757]]]])
